#???
server:
  port: 8080
#??????
qq:
  bot:
    app-id:   #?????AppID
    client-secret:   #?????AppSecret
    token-refresh-buffer-seconds: 300  #token??
#??
logging:
  level:
    root: info
  file:
    name: E:\qq\bot.log  #????