#???
server:
  port: 8080
#??????
qq:
  bot:
    app-id: 102067315  #?????AppID
    client-secret: 0peUKA0qgWNE5wneWOG80sleXQJC5ztn  #?????AppSecret
    token-refresh-buffer-seconds: 300  #token??
#??
logging:
  level:
    root: info
  file:
    name: E:\qq\bot.log  #????
#????
#??????  ???????????????? 80?443?8080?8443